### ISSUE TITLE
Crashes when `enableActivityMetrics` is false

### ISSUE THREAD

**Issue by codebymikey** [frogermcs/AndroidDevMetrics#28]
AndroidDevMetrics crashes when running with the following configuration:

```
AndroidDevMetrics.Builder builder = new AndroidDevMetrics.Builder(this)
            .enableActivityMetrics(false)
            .enableDagger2Metrics(true)
            .showNotification(false);
AndroidDevMetrics.initWith(builder);`
```

The stack trace is as follow:

```
Caused by: java.lang.RuntimeException: MethodsTracingManager must be initialized by init(..)
at com.frogermcs.androiddevmetrics.internal.MethodsTracingManager.checkInitialized(MethodsTracingManager.java:90)
at com.frogermcs.androiddevmetrics.internal.MethodsTracingManager.shouldTraceMethod(MethodsTracingManager.java:84)
at com.frogermcs.androiddevmetrics.aspect.ActivityLifecycleAnalyzer.executeWithTracingIfEnabled(ActivityLifecycleAnalyzer.java:77)
at com.frogermcs.androiddevmetrics.aspect.ActivityLifecycleAnalyzer.ajc$inlineAccessMethod$com_frogermcs_androiddevmetrics_aspect_ActivityLifecycleAnalyzer$com_frogermcs_androiddevmetrics_aspect_ActivityLifecycleAnalyzer$executeWithTracingIfEnabled(ActivityLifecycleAnalyzer.java:1)
at com.frogermcs.androiddevmetrics.aspect.ActivityLifecycleAnalyzer.logAndExecute(ActivityLifecycleAnalyzer.java:66)
```

**Comment by maciej-kaznowski** [comment]
Getting the same issue when not initialising the library on a debug build:
`if (internalPreferenceManager.isAndroidDevMetricsEnabled()) AndroidDevMetrics.initWith(this);`
